name: Render GitHub Action
description: GitHub Action to check a Render deployment status
author: Bounce Inc.
inputs:
  email:
    required: true
    description: User email used to sign-in to Render's API
  password:
    required: true
    description: User password used to sign-in to Render's API
  service-id:
    required: true
    description: The id of the Render service to be tracked
  token:
    required: true
    description: GitHub token
  sleep:
    required: false
    description: Sleep time between the render deployment success and setting the Github deployment as successful
    default: '0'
  retries:
    required: false
    description: 'Maximum number of retries trying to find the deployment. Note: Retries will be attempted every 5 seconds'
    default: '50'
runs:
  using: node12
  main: dist/index.js
