name: Render GitHub Action
description: GitHub Action to check a Render deployment status
author: Bounce Inc.
inputs:
  email:
    required: true
    description: User email used to sign-in to Render's API
  password:
    required: true
    description: User password used to sign-in to Render's API
  service-id:
    required: true
    description: The id of the Render service to be tracked
  token:
    required: true
    description: GitHub token
runs:
  using: node12
  main: dist/index.js
