name: Render GitHub Action
description: GitHub Action to check a Render deployment status
author: Bounce Inc.
inputs:
  email:
    required: true
    description: Render user email
  password:
    required: true
    description: Render password
  service-id:
    required: true
    description: Render service id
runs:
  using: node12
  main: dist/index.js
